apiVersion: v1
kind: Template
metadata:
  name: "vault-token-renewal-cron-job"
parameters:
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    labels:
      app: "vault-token-renewal-cron-job"
    name: "vault-token-renewal-cron-job"
  spec:
    schedule: "0 3 * * 6"
    ConcurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              parent: "vault-token-renewal-cron-job"
          spec:
            restartPolicy: OnFailure
            serviceAccountName: vault-auth
            containers:
              - name: "vault-token-renewal-cron-job"
                image: "image-registry.openshift-image-registry.svc:5000/vault/vault-unsealer:latest"
# - apiVersion: rbac.authorization.k8s.io/v1
#   kind: RoleBinding
#   metadata:
#     name: read-secrets
#     namespace: vault
#   subjects:
#   - kind: ServiceAccount
#     name: vault-auth
#   resources: ["secrets"]
#   verbs: ["get", "update"]