apiVersion: v1
kind: Template
metadata:
  name: "vault-unsealer-cron-job"
parameters:
  - name: SECRET_PATH
    required: true
  - name: IMPORT_VAULT_ADDR
    required: true
  - name: EXPORT_VAULT_ADDR
    required: true

objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    labels:
      app: "vault-backup-cron-job"
    name: "vault-backup-cron-job"
  spec:
    schedule: "35 0 * * 6"
    ConcurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              parent: "vault-backup-cron-job"
          spec:
            restartPolicy: OnFailure
            serviceAccountName: vault-backup-serviceaccount
            containers:
              - name: "vault-backup-cron-job"
                env:
                  - name: SECRET_PATH
                    valueFrom:
                      configMapKeyRef:
                        key: SECRET_PATH
                        name: "vault-backup-cron-job"
                  - name: IMPORT_VAULT_TOKEN
                    valueFrom:
                      secretKeyRef:
                        key: IMPORT_VAULT_TOKEN
                        name: "vault-backup-cron-job"
                  - name: EXPORT_VAULT_TOKEN
                    valueFrom:
                      secretKeyRef:
                        key: EXPORT_VAULT_TOKEN
                        name: "vault-backup-cron-job"